# Generated by Django 3.1 on 2020-09-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
